### ISSUE TITLE
react-content-query-webpart stopped working

### ISSUE THREAD

**Issue by sam575815** [spplante/react-content-query#21]
We are using react-content-query-webpart from last 6 weeks and its working and we implemented almost in 100+pages. Suddenly the webpart started throwing the following error. Any thoughts and help would be appreciated. 

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_2.2.1. Store had [3.0.2]. Service worker version: odsp-web-prod_2024-07-26.005; App version: odsp-web-prod_2024-07-26.007; Next app version: odsp-web-prod_2024-07-26.007

CALL STACK:
Error: Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_2.2.1. Store had [3.0.2]. Service worker version: odsp-web-prod_2024-07-26.005; App version: odsp-web-prod_2024-07-26.007; Next app version: odsp-web-prod_2024-07-26.007
    at e.getManifest (https://res-2-gcc.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_07a02c7eec50837d6dc390d72fa1b8a6.js:207:5083)
    at e.requestManifest (https://res-2-gcc.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_07a02c7eec50837d6dc390d72fa1b8a6.js:207:7401)
    at e._configureComponentResource (https://res-2-gcc.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_07a02c7eec50837d6dc390d72fa1b8a6.js:199:9476)
    at e.configLoadComponent (https://res-2-gcc.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_07a02c7eec50837d6dc390d72fa1b8a6.js:199:7324)
    at e._loadComponent (https://res-2-gcc.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_07a02c7eec50837d6dc390d72fa1b8a6.js:199:12715)
    at e.loadComponent (https://res-2-gcc.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_07a02c7eec50837d6dc390d72fa1b8a6.js:209:346)
    at https://res-2-gcc.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_07a02c7eec50837d6dc390d72fa1b8a6.js:199:11071
    at new Promise (<anonymous>)
    at e.loadComponent (https://res-2-gcc.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_07a02c7eec50837d6dc390d72fa1b8a6.js:199:10957)
    at e.loadComponent (https://res-2-gcc.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_07a02c7eec50837d6dc390d72fa1b8a6.js:199:2270)

**Comment by spplante** [comment]
@sam575815 Project has been moved to the link below, please open your issue over there as it is not actively maintained here:

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-content-query-online

Thanks!
